name: CrownCore
version: 1.1.8
main: de.obey.crown.core.CrownCore
author: Obey
website: dsc.gg/crownplugins
api-version: '1.20'
folia-supported: true

softdepend:
  - PlaceholderAPI
  - Vault

commands:
  location:
  crowncore:
